#ifndef BOARD_DEFAULTS_H
#define BOARD_DEFAULTS_H

const char* const JSON_BOARD_DEFAULTS =

#if defined(ARDUINO_M5Stick_C)
      "\"Pins\": {"
        "\"0\": \"GPIO0 - ADC2_1,TOUCH1\","
#if defined(ARDUINO_M5Stick_C_Plus)
        "\"25\": \"GPIO25 - ADC2_8,DAC_1\","
#endif
        "\"26\": \"GPIO26 - ADC2_9,DAC_2\","
        "\"32\": \"GPIO32 - ADC1_4,TOUCH9,XTAL32\","
        "\"33\": \"GPIO33 - ADC1_5,TOUCH8,XTAL32\","
        "\"36\": \"GPIO36 - ADC1_0,SensVP\","
        "\"37\": \"GPIO37 - BTN\","
        "\"39\": \"GPIO39 - BTN\""
      "},"
      "\"Default\": {"
        "\"pin_rx\": 36,"
        "\"pin_tx\": 26,"
        "\"pin_heating\": 0,"
        "\"pin_cooling\": 0,"
        "\"pin_sg1\": 32,"
        "\"pin_sg2\": 33,"
        "\"uart\": {"
          "\"pin_rx\": 32,"
          "\"pin_tx\": 33"
        "},"
        "\"spi\": {"
          "\"mosi\": 26,"
          "\"miso\": 0,"
          "\"sck\": 36,"
          "\"cs\": 32,"
          "\"int\": 33,"
          "\"mhz\": 12"
        "},"
        "\"can_speed_kbps\": 20,"
        "\"can_mqtt_topic_name\": \"CAN/\","
        "\"can_autopoll_time\": 30,"
        "\"pin_enable_config\": 39,"
        "\"frequency\": 30000,"
        "\"mqtt_topic_name\": \"espaltherma/\","
        "\"mqtt_onetopic_name\": \"OneATTR/\","
        "\"mqtt_port\": 1883"
      "}"
    "}"
#elif defined(ESP32)
      "\"Pins\": {"
        "\"0\": \"GPIO0 - ADC2_1,TOUCH1\","
        "\"1\": \"GPIO1 - U0_TXD,CLK3\","
        "\"2\": \"GPIO2 - ADC2_2,TOUCH2,CS\","
        "\"3\": \"GPIO3 - U0_RXD,CLK2\","
        "\"4\": \"GPIO4 - ADC2_0,TOUCH0\","
        "\"5\": \"GPIO5 - VSPI_CS\","
        "\"12\": \"GPIO12 - ADC2_5,TOUCH5,HSPI_MISO\","
        "\"13\": \"GPIO13 - ADC2_4,TOUCH4,HSPI_MOSI\","
        "\"14\": \"GPIO14 - ADC2_6,TOUCH6,HSPI_CLK\","
        "\"15\": \"GPIO15 - ADC2_3,TOUCH3,HSPI_CS\","
        "\"16\": \"GPIO16 - U2_RXD\","
        "\"17\": \"GPIO17 - U2_TXD\","
        "\"18\": \"GPIO18 - SCK,VSPI_CLK\","
        "\"19\": \"GPIO19 - MISO,VSPI_MISO\","
        "\"21\": \"GPIO21 - SDA\","
        "\"22\": \"GPIO22 - SCL\","
        "\"23\": \"GPIO23 - MOSI,VSPI_MOSI\","
        "\"25\": \"GPIO25 - ADC2_8,DAC_1\","
        "\"26\": \"GPIO26 - ADC2_9,DAC_2\","
        "\"27\": \"GPIO27 - ADC2_7,TOUCH7\","
        "\"32\": \"GPIO32 - ADC1_4,TOUCH9,XTAL32\","
        "\"33\": \"GPIO33 - ADC1_5,TOUCH8,XTAL32\","
        "\"34\": \"GPIO34 - ADC1_6\","
        "\"35\": \"GPIO35 - ADC1_7\","
        "\"36\": \"GPIO36 - ADC1_0,SensVP\","
        "\"39\": \"GPIO39 - ADC1_3,SensVN\""
      "},"
      "\"Default\": {"
        "\"pin_rx\": 16,"
        "\"pin_tx\": 17,"
        "\"pin_heating\": 13,"
        "\"pin_cooling\": 14,"
        "\"pin_sg1\": 32,"
        "\"pin_sg2\": 33,"
        "\"uart\": {"
          "\"pin_rx\": 4,"
          "\"pin_tx\": 5"
        "},"
        "\"spi\": {"
          "\"mosi\": 23,"
          "\"miso\": 19,"
          "\"sck\": 18,"
          "\"cs\": 5,"
          "\"int\": 4,"
          "\"mhz\": 12"
        "},"
        "\"can_speed_kbps\": 20,"
        "\"can_mqtt_topic_name\": \"CAN/\","
        "\"can_autopoll_time\": 30,"
        "\"pin_enable_config\": 27,"
        "\"frequency\": 30000,"
        "\"mqtt_topic_name\": \"espaltherma/\","
        "\"mqtt_onetopic_name\": \"OneATTR/\","
        "\"mqtt_port\": 1883"
      "}"
#else
    "\"Pins\": {},"
    "\"Default\": {}"
#endif
;

#endif