"""Embeds the web interface (web/index.html with the translations of web/i18n/, gzipped) into include/webui_data.h.

Runs as a PlatformIO pre-build script (extra_scripts = pre:scripts/build_web.py), or standalone:
    python scripts/build_web.py
The header is only rewritten when the page changes, so builds are not needlessly recompiled.
"""

import gzip
import io
import os
import sys

try:
    Import("env")  # noqa: F821 - defined when running as a PlatformIO extra script
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

OUTPUT = os.path.join(ROOT, "include", "webui_data.h")
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import webpage  # noqa: E402


def main():
    page = webpage.render(ROOT).encode("utf-8")
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(page)
    data = buf.getvalue()

    lines = [
        "// Generated by scripts/build_web.py from web/index.html and web/i18n/ - DO NOT EDIT.",
        "// %d bytes, %d gzipped." % (len(page), len(data)),
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "static const size_t WEBUI_INDEX_GZ_LEN = %d;" % len(data),
        "static const uint8_t WEBUI_INDEX_GZ[] = {",
    ]
    for i in range(0, len(data), 20):
        lines.append("    " + ",".join("0x%02x" % b for b in data[i:i + 20]) + ",")
    lines.append("};")
    lines.append("")
    content = "\n".join(lines)

    current = None
    if os.path.exists(OUTPUT):
        with open(OUTPUT, encoding="utf-8") as f:
            current = f.read()
    if current != content:
        with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        print("build_web: include/webui_data.h updated (%d bytes gzipped)" % len(data))


main()
