// Generated by scripts/gen_catalog.py from include/def/*.h - DO NOT EDIT.
// 34 models, 646 entries, 7330 label bytes.
#pragma once

#define CATALOG_MODEL_COUNT 34
#define CATALOG_ENTRY_COUNT 646

// name, family, protocol, capacity range in kW from the name (0: not told)
static const CatalogModel CATALOG_MODELS[CATALOG_MODEL_COUNT] = {
    {"Altherma(EBLA-EDLA D series 4-8kW Monobloc)", 'G', 'I', 4, 8},
    {"Altherma(EBLA-EDLA D series 9-16kW Monobloc)", 'G', 'I', 9, 16},
    {"Altherma(EGSAH-X-EWSAH-X-D series 6-10kW GEO3)", 'G', 'I', 6, 10},
    {"Altherma(EGSQH-A series 10kW GEO2)", 'L', 'I', 10, 10},
    {"Altherma(EPGA D EAB-EAV-EAVZ D(J) series 11-16kW)", 'G', 'I', 11, 16},
    {"Altherma(EPRA D ETSH-X 16P30-50 D series 14-16kW-ECH2O)", 'G', 'I', 14, 16},
    {"Altherma(EPRA D ETV16-ETB16-ETVZ16 D series 14-16kW)", 'G', 'I', 14, 16},
    {"Altherma(EPRA D_D7 ETSH-X 16P30-50 E_E7 series 14-18kW-ECH2O)", 'G', 'I', 14, 18},
    {"Altherma(EPRA D_D7 ETV16-ETB16-ETVZ16 E_E7 series 14-18kW)", 'G', 'I', 14, 18},
    {"Altherma(EPRA E ETSH-X 16P30-50 E series 8-12kW-ECH2O)", 'G', 'I', 8, 12},
    {"Altherma(EPRA E ETV16-ETB16-ETVZ16 E_EJ series 8-12kW)", 'G', 'I', 8, 12},
    {"Altherma(ERGA D EHSH-X P30-50 D series 04-08kW-ECH2O)", 'L', 'I', 4, 8},
    {"Altherma(ERGA D EHV-EHB-EHVZ DA series 04-08kW)", 'L', 'I', 4, 8},
    {"Altherma(ERGA D EHV-EHB-EHVZ DJ series 04-08 kW)", 'G', 'I', 4, 8},
    {"Altherma(ERGA E EHSH-X P30-50 E_EF series 04-08kW-ECH2O)", 'G', 'I', 4, 8},
    {"Altherma(ERGA E EHV-EHB-EHVZ E_EJ series 04-08kW)", 'G', 'I', 4, 8},
    {"Altherma(ERLA D EBSH-X 16P30-50 D SERIES 11-16kW-ECH2O)", 'G', 'I', 11, 16},
    {"Altherma(ERLA D EBV-EBB-EBVZ D SERIES 11-16kW)", 'G', 'I', 11, 16},
    {"Altherma(ERLA03 D EHFH-EHFZ DJ series 3kW)", 'L', 'I', 3, 3},
    {"Altherma(Hybrid)", 'L', 'I', 0, 0},
    {"Altherma(LT_CA_CB_04-08kW)", 'L', 'I', 4, 8},
    {"Altherma(LT_CA_CB_11-16kW)", 'L', 'I', 11, 16},
    {"Altherma(LT_CB_04-08kW Bizone)", 'L', 'I', 4, 8},
    {"Altherma(LT_CB_11-16kW Bizone)", 'L', 'I', 11, 16},
    {"Altherma(LT_EBLQ-EBLQ-CA series 5-7kW Monobloc)", 'L', 'I', 5, 7},
    {"Altherma(LT_EBLQ-EDLQ-CA series 11-16kW Monobloc)", 'L', 'I', 11, 16},
    {"Altherma(LT_Multi_DHWHP)", 'L', 'I', 0, 0},
    {"Altherma(LT_Multi_Hybrid)", 'L', 'I', 0, 0},
    {"Daikin Mini chiller(EWAA-EWYA D series 4-8kW)", 'G', 'I', 4, 8},
    {"Daikin Mini chiller(EWAA-EWYA D series 9-16kW)", 'L', 'I', 9, 16},
    {"Daikin Mini chiller(EWAQ-EWYQ B series 4-8kW)", 'L', 'I', 4, 8},
    {"EKHWET-BAV3(Multi DHW tank)", 'G', 'I', 0, 0},
    {"PROTOCOL_S", 'S', 'S', 0, 0},
    {"PROTOCOL_S_ROTEX", 'R', 'S', 0, 0},
};

static const char CATALOG_LABELS[] =
    "*Refrigerant type" "\0"
    "Sensor Data Qty" "\0"
    "INV compressor Qty" "\0"
    "STD compressor Qty" "\0"
    "Fan Data Qty" "\0"
    "Expansion Valve Data Qty" "\0"
    "4 Way Valve Data Qty" "\0"
    "Crank Case Heater Qty" "\0"
    "Solenoid valve Qty" "\0"
    "Max. connectable indoor units" "\0"
    "Connected Indoor Unit Qty" "\0"
    "O/U MPU ID (xx)" "\0"
    "O/U MPU ID (yy)" "\0"
    "O/U capacity (kW)" "\0"
    "Operation Mode" "\0"
    "Thermostat ON/OFF" "\0"
    "Restart standby" "\0"
    "Startup Control" "\0"
    "Defrost Operation" "\0"
    "Oil Return Operation" "\0"
    "Pressure equalizing operation" "\0"
    "Demand Signal" "\0"
    "Low noise control" "\0"
    "Error type" "\0"
    "Error Code" "\0"
    "Target Evap. Temp." "\0"
    "DHW supply temperature" "\0"
    "Target Cond. Temp." "\0"
    "Discharge Temp. Drop" "\0"
    "Discharge Temp. Protection Retry Qty" "\0"
    "Comp. INV Current Drop" "\0"
    "Comp. INV Current Protection Retry Qty" "\0"
    "HP Drop Control" "\0"
    "HP Protection Retry Qty" "\0"
    "LP Drop Control" "\0"
    "LP Protection Retry Qty" "\0"
    "Fin Temp. Drop Control" "\0"
    "Fin Temp. Protection Retry Qty" "\0"
    "Other Drop Control" "\0"
    "Not in use" "\0"
    "O/U EEPROM (1st digit)" "\0"
    "O/U EEPROM (3rd 4th digit)" "\0"
    "O/U EEPROM (5th 6th digit)" "\0"
    "O/U EEPROM (7th 8th digit)" "\0"
    "O/U EEPROM (10th digit)" "\0"
    "O/U EEPROM (11th digit)" "\0"
    "R1T-Outdoor air temp." "\0"
    "O/U Heat Exch. Temp." "\0"
    "O/U Heat Exch. Temp.(R4T)" "\0"
    "2 phase thermistor (R4T)" "\0"
    "Discharge pipe temp." "\0"
    "Discharge pipe temp.(R2T)" "\0"
    "Suction pipe temp." "\0"
    "Suction pipe temp.(R3T)" "\0"
    "Heat exchanger mid-temp." "\0"
    "Heat exchanger mid-temp.(R5T)" "\0"
    "Entering brine temp.(R5T)" "\0"
    "Liquid temperature(R3T)" "\0"
    "Liquid pipe temp.(R6T)" "\0"
    "Leaving brine temp.(R6T)" "\0"
    "High Pressure" "\0"
    "High Pressure(T)" "\0"
    "Low Pressure" "\0"
    "Low Pressure(T)" "\0"
    "Pressure" "\0"
    "Pressure(T)" "\0"
    "INV primary current (A)" "\0"
    "INV secondary current (A)" "\0"
    "INV fin temp." "\0"
    "Fan1 Fin temp." "\0"
    "Brine inlet temp." "\0"
    "Fan2 Fin temp." "\0"
    "Brine outlet temp." "\0"
    "Compressor outlet temperature" "\0"
    "Refrig. temp. evap.Out" "\0"
    "Injection tube temperature" "\0"
    "INV frequency (rps)" "\0"
    "Solenoid Valve 4" "\0"
    "Solenoid Valve 5" "\0"
    "Fan 1 (step)" "\0"
    "Brine pump feedback" "\0"
    "Fan 1 (10 rpm)" "\0"
    "Fan 2 (step)" "\0"
    "Expansion valve 1 (pls)" "\0"
    "Expansion valve 2 (pls)" "\0"
    "Expansion valve 3 (pls)" "\0"
    "4 Way Valve 1" "\0"
    "4 Way Valve 2" "\0"
    "4 Way Valve 3" "\0"
    "4 Way Valve 4" "\0"
    "4 Way Valve 5" "\0"
    "4 Way Valve 6" "\0"
    "4 Way Valve 7" "\0"
    "4 Way Valve 8" "\0"
    "Crank case heater" "\0"
    "Expansion valve 4 (pls)" "\0"
    "Hot gas bypass valve (Y2S)" "\0"
    "LP bypass valve (Y3S)" "\0"
    "Inlet water temp. (DMW)" "\0"
    "4 Way Valve" "\0"
    "Outlet water heat exchanger temp (hydro split model) DLWB2" "\0"
    "Y1S" "\0"
    "SV (drain pan heater)" "\0"
    "Y3S" "\0"
    "Hot gas bypass valve (Y3S)" "\0"
    "LP bypass valve (Y2S)" "\0"
    "4 way valve (Y1S)" "\0"
    "Y2S" "\0"
    "DHW:SV1" "\0"
    "Drain pan heater" "\0"
    "RA:SV2" "\0"
    "Data Enable/Disable" "\0"
    "Indoor Unit Address" "\0"
    "I/U operation mode" "\0"
    "Ext. Thermostat ON/OFF" "\0"
    "Freeze Protection" "\0"
    "Silent Mode" "\0"
    "Freeze Protection for water piping" "\0"
    "Error detailed code" "\0"
    "I/U capacity code" "\0"
    "Indoor Unit Capacity" "\0"
    "DHW setpoint" "\0"
    "LW setpoint (main)" "\0"
    "Water flow switch" "\0"
    "Thermal protector (Q1L) BUH" "\0"
    "Thermal protector BSH" "\0"
    "Benefit kWh rate power supply" "\0"
    "Solar input" "\0"
    "SmartGridContact2" "\0"
    "SmartGridContact1" "\0"
    "Bivalent Operation" "\0"
    "2way valve(On:Heat_Off:Cool)" "\0"
    "3way valve(On:DHW_Off:Space)" "\0"
    "BSH" "\0"
    "BUH Step1" "\0"
    "BUH Step2" "\0"
    "Floor loop shut off valve" "\0"
    "Water pump operation" "\0"
    "Solar pump operation" "\0"
    "Indoor Option Code" "\0"
    "I/U Software ID (yy)" "\0"
    "I/U Software ID (xx)" "\0"
    "I/U EEPROM Ver." "\0"
    "Leaving water temp. before BUH (R1T)" "\0"
    "[HPSU] Tv inflow Temp  (R1T)" "\0"
    "Leaving water temp. after BUH (R2T)" "\0"
    "[HPSU] Tvbh inflow Temp after Buffer/BUH (R2T)" "\0"
    "Refrig. Temp. liquid side (R3T)" "\0"
    "Inlet water temp.(R4T)" "\0"
    "DHW tank temp. (R5T)" "\0"
    "Indoor ambient temp. (R1T)" "\0"
    "Ext. indoor ambient sensor (R6T)" "\0"
    "Ext. outdoor ambient sensor (R6T)" "\0"
    "Reheat ON/OFF" "\0"
    "Storage ECO ON/OFF" "\0"
    "Storage comfort ON/OFF" "\0"
    "Powerful DHW Operation. ON/OFF" "\0"
    "Space heating Operation ON/OFF" "\0"
    "System OFF (ON:System off)" "\0"
    "Emergency (indoor) active/not active" "\0"
    "LW setpoint (add)" "\0"
    "RT setpoint" "\0"
    "Add. Ext. RT Input Cool." "\0"
    "Add. Ext. RT Input Heat." "\0"
    "Main RT Cooling" "\0"
    "Main RT Heating" "\0"
    "Pwr consumption limit 4" "\0"
    "Pwr consumption limit 3" "\0"
    "Pwr consumption limit 2" "\0"
    "Pwr consumption limit 1" "\0"
    "None" "\0"
    "PHE Heater" "\0"
    "Tank preheat ON/OFF" "\0"
    "Circulation pump operation" "\0"
    "Alarm output" "\0"
    "Space H Operation output" "\0"
    "Pump Feedback (bit7)" "\0"
    "Pump Feedback (bit6)" "\0"
    "Pump Feedback (bit5)" "\0"
    "Pump pwm fdbk  (0:Stby 1:On 2:warning 3:elec err 4:blocked)" "\0"
    "Flow sensor (l/min)" "\0"
    "Water pressure" "\0"
    "Water pump signal (0:max-100:stop)" "\0"
    "[Future] 3 way Valve Mixing 1" "\0"
    "[Future] 3 way Valve Mixing 2" "\0"
    "Refrigerant pressure sensor" "\0"
    "Pressure sensor(T)" "\0"
    "I/U EEPROM (3rd digit)" "\0"
    "I/U EEPROM (4th 5th digit)" "\0"
    "I/U EEPROM (6th 7th digit)" "\0"
    "I/U EEPROM (8th 9th digit)" "\0"
    "I/U EEPROM (11th digit)" "\0"
    "I/U EEPROM (12th digit)(rev.)" "\0"
    "[HPSU] Mixed leaving water temperature after the tank R7T (DLWA2)" "\0"
    "Mixed water temp.(R7T)" "\0"
    "[HPSU] Tank valve position (0:Bypass 100:Tank)" "\0"
    "[RT space thermo ON/OFF] (bit1)" "\0"
    "[HPSU] Bypass valve position (0:Bypass 100:Emitter)" "\0"
    "[RT space thermo ON/OFF] (bit0)" "\0"
    "RT Control State (0:thermo off 1:thermo on 2:buffering)" "\0"
    "[HPSU] Tank state (1:preheat 2:support 3:excess)" "\0"
    "[HPSU] Tank DHW bivalent output signal" "\0"
    "[HPSU] Tank DHW bivalent primary heat source (OFF:HP  ON:Boiler)" "\0"
    "[HPSU] Tank heating bivalent output signal" "\0"
    "[HPSU] Tank heating bivalent primary heat source (OFF:HP  ON:Boiler)" "\0"
    "BUH output capacity" "\0"
    "Current measured by CT sensor of L1" "\0"
    "Current measured by CT sensor of L2" "\0"
    "HP Forced FG" "\0"
    "Current measured by CT sensor of L3" "\0"
    "HP is operation forced OFF by installer" "\0"
    "Hybrid Op. Mode" "\0"
    "Boiler Operation Demand" "\0"
    "Boiler DHW Demand" "\0"
    "Bypass Valve Output" "\0"
    "DHW in standby due to defrost in ODU" "\0"
    "Defrost" "\0"
    "Powerful demand" "\0"
    "DHW priority request" "\0"
    "Mode conflict (DHW in standby)" "\0"
    "Add pump" "\0"
    "Main pump" "\0"
    "BSH allowance Multi" "\0"
    "BE_COP" "\0"
    "Hybrid Heating Target Temp." "\0"
    "Boiler Heating Target Temp." "\0"
    "Mixed water temp." "\0"
    "2nd Domestic hot water temperature" "\0"
    "Target delta T heating" "\0"
    "Target delta T cooling" "\0"
    "[EKMIK] Bizone kit mixed leaving water temperature R1T" "\0"
    "[EKMIK] Bizone kit mix valve position M1S" "\0"
    "Suction temp" "\0"
    "Outdoor heat exchanger temp." "\0"
    "Liquid pipe temp." "\0"
    "O/U MPU ID" "\0"
    "HPS operation" "\0"
    "Safeguard operation" "\0"
    "Solenoid Valve 3" "\0"
    "Solenoid Valve 1" "\0"
    "52C Output" "\0"
    "Solenoid Valve 2" "\0"
    "During emergency operation" "\0"
    "Indoor unit blowout 50 ° C flag" "\0"
    "Powerful bit (MT setting bit)" "\0"
    "Compressor port temperature" "\0"
    "(Raw data)Water heat exchanger inlet temp." "\0"
    "(Raw data)Water heat exchanger outlet temp." "\0"
    "Liquid INJ solenoid valve (Y4S)" "\0"
    "Bottom Plate Heater" "\0"
    "Target Discharge Temp." "\0"
    "Target port temperature" "\0"
    "Monobloc setting" "\0"
    "Minichiller setting" "\0"
    "MT setting" "\0"
    "GSHP setting" "\0"
    "Hydro split setting" "\0"
    "Alterma LT setting" "\0"
    "Outdoor air temp." "\0"
    "Suction Pipe Temperature" "\0"
    "O/U Heat Exch. Mid-temp." "\0"
    "Outdoor heat exchanger mid temp." "\0"
    "Heat sink temp.(R10T)" "\0"
    "Heat sink temp." "\0"
    "Fin Temp." "\0"
    "Pressure sensor" "\0"
    "Voltage (N-phase) (V)" "\0"
    "Voltage (V)" "\0"
    "Brine Flow Switch" "\0"
    "Refrig. temp. evap. In" "\0"
    "STD Compressor 1" "\0"
    "STD Compressor 2" "\0"
    "Expansion valve (pls)" "\0"
    "Crank case heater 2" "\0"
    "Crank case heater 3" "\0"
    "Crank case heater 4" "\0"
    "SV (hot Gas)" "\0"
    "SV (BPH)" "\0"
    "Crank case heater 1" "\0"
    "Crank case heater 5" "\0"
    "SV1 (hot gas)" "\0"
    "SV2 (BPH)" "\0"
    "INV frequency 2 (rps)" "\0"
    "Expansion valve 5 (pls)" "\0"
    "Indoor Unit Code" "\0"
    "Thermal Protector BUH" "\0"
    "BPH" "\0"
    "Outlet Water Heat Exch. Temp. (R1T)" "\0"
    "Outlet Water BUH Temp. (R2T)" "\0"
    "[HPSU] Tr return Temp (R4T)" "\0"
    "RT Temp." "\0"
    "Outdoor Ambient or Ext Sensor" "\0"
    "Space C/H Op. or BPH" "\0"
    "Defrost prohibition ON/OFF" "\0"
    "Mode conflict" "\0"
    "3 way Valve Mixing 1" "\0"
    "3 way Valve Mixing 2" "\0"
    "Hybrid DHW operation mode" "\0"
    "HP Sensor(kgcm2)" "\0"
    "LP Sensor(kgcm2)" "\0"
    "EV (pls)" "\0"
    "Outdoor Fan (Upper)(rps)" "\0"
    "Outdoor Fan (Lower)(rps)" "\0"
    "INV Comp. Frequency(Hz)" "\0"
    "Comp. Preheat" "\0"
    "20S (4-way) Output" "\0"
    "20R (SV) Output" "\0"
    "Crankcase Heater" "\0"
    "Ener-Cut Output" "\0"
    "Indoor Suction Air Temp.(C)" "\0"
    "Indoor Heat Exchanger Temp.(C)" "\0"
    "Outdoor air temp.(C)" "\0"
    "Outdoor heat exchanger temp.(C)" "\0"
    "Discharge pipe temp.(C)" "\0"
    "Fin Temp.(C)" "\0"
    "Delta-Tr(deg)" "\0"
    "R/C Setpoint(C)" "\0"
    "Thermo Off Error" "\0"
    "Warning Code" "\0"
    "Caution Code" "\0"
    "Circulation pump" "\0"
    "External heater?" "\0"
    "Priority to domestic water" "\0"
    "Burner inhibit from solaris" "\0"
    "Refrig. Temp. liquid side(C)" "\0"
    "Inlet water temp.(C)" "\0"
    "Outlet Water Temp.(C)" "\0"
    "D(C)" "\0"
    "DHW tank temp.(C)" "\0"
    "F(C)" "\0"
    "????" "\0"
    ;

// reg, offset, conv, size, type, label, flags, models
static const CatalogEntry CATALOG_ENTRIES[CATALOG_ENTRY_COUNT] = {
    {0x00, 0, 802, 0, -1, 0, 2, 0x000000009003e7f7ULL},
    {0x00, 0, 152, 1, -1, 18, 0, 0x000000009003e7f7ULL},
    {0x00, 1, 152, 1, -1, 34, 0, 0x000000009003e7f7ULL},
    {0x00, 2, 152, 1, -1, 53, 0, 0x000000009003e7f7ULL},
    {0x00, 3, 152, 1, -1, 72, 0, 0x000000009003e7f7ULL},
    {0x00, 4, 152, 1, -1, 85, 0, 0x000000009003e7f7ULL},
    {0x00, 5, 152, 1, -1, 110, 0, 0x000000009003e7f7ULL},
    {0x00, 6, 152, 1, -1, 131, 0, 0x000000009003e7f7ULL},
    {0x00, 7, 152, 1, -1, 153, 0, 0x000000009003e7f7ULL},
    {0x00, 8, 152, 1, -1, 172, 0, 0x000000009003e7f7ULL},
    {0x00, 9, 152, 1, -1, 202, 0, 0x000000009003e7f7ULL},
    {0x00, 10, 152, 1, -1, 228, 0, 0x000000009003e7f7ULL},
    {0x00, 11, 152, 1, -1, 244, 0, 0x000000009003e7f7ULL},
    {0x00, 12, 105, 1, -1, 260, 0, 0x000000009003e7f7ULL},
    {0x10, 0, 217, 1, -1, 278, 1, 0x000000009003e7f7ULL},
    {0x10, 1, 307, 1, -1, 293, 1, 0x000000009003e7f7ULL},
    {0x10, 1, 306, 1, -1, 311, 0, 0x000000009003e7f7ULL},
    {0x10, 1, 305, 1, -1, 327, 0, 0x000000009003e7f7ULL},
    {0x10, 1, 304, 1, -1, 343, 1, 0x000000009003e7f7ULL},
    {0x10, 1, 303, 1, -1, 361, 0, 0x000000009003e7f7ULL},
    {0x10, 1, 302, 1, -1, 382, 0, 0x000000009003e7f7ULL},
    {0x10, 1, 301, 1, -1, 412, 0, 0x000000009003e7f7ULL},
    {0x10, 1, 300, 1, -1, 426, 0, 0x000000009003e7f7ULL},
    {0x10, 4, 203, 1, -1, 444, 1, 0x000000009003e7f7ULL},
    {0x10, 5, 204, 1, -1, 455, 1, 0x000000009003e7f7ULL},
    {0x10, 6, 114, 2, 1, 466, 0, 0x000000001003e7f7ULL},
    {0x10, 6, 114, 2, 1, 485, 0, 0x0000000080000000ULL},
    {0x10, 8, 114, 2, 1, 508, 0, 0x000000009003e7f7ULL},
    {0x10, 10, 307, 1, -1, 527, 0, 0x000000009003e7f7ULL},
    {0x10, 10, 310, 1, -1, 548, 0, 0x000000009003e7f7ULL},
    {0x10, 10, 303, 1, -1, 585, 0, 0x000000009003e7f7ULL},
    {0x10, 10, 311, 1, -1, 608, 0, 0x000000009003e7f7ULL},
    {0x10, 11, 307, 1, -1, 647, 0, 0x000000009003e7f7ULL},
    {0x10, 11, 310, 1, -1, 663, 0, 0x000000009003e7f7ULL},
    {0x10, 11, 303, 1, -1, 687, 0, 0x000000009003e7f7ULL},
    {0x10, 11, 311, 1, -1, 703, 0, 0x000000009003e7f7ULL},
    {0x10, 12, 307, 1, -1, 727, 0, 0x000000009003e7f7ULL},
    {0x10, 12, 310, 1, -1, 750, 0, 0x000000009003e7f7ULL},
    {0x10, 12, 303, 1, -1, 781, 0, 0x000000009003e7f7ULL},
    {0x10, 12, 311, 1, -1, 800, 0, 0x000000009003e7f7ULL},
    {0x11, 0, 215, 1, -1, 811, 0, 0x000000009003e7f7ULL},
    {0x11, 1, 215, 1, -1, 834, 0, 0x000000009003e7f7ULL},
    {0x11, 2, 215, 1, -1, 861, 0, 0x000000009003e7f7ULL},
    {0x11, 3, 215, 1, -1, 888, 0, 0x000000009003e7f7ULL},
    {0x11, 4, 215, 1, -1, 915, 0, 0x000000009003e7f7ULL},
    {0x11, 5, 214, 1, -1, 939, 0, 0x000000009003e7f7ULL},
    {0x20, 0, 105, 2, 1, 963, 1, 0x000000009003e7f7ULL},
    {0x20, 2, 105, 2, 1, 985, 0, 0x000000009000e001ULL},
    {0x20, 2, 105, 2, 1, 1006, 0, 0x00000000000307f2ULL},
    {0x20, 2, 105, 2, 1, 1032, 0, 0x0000000000000004ULL},
    {0x20, 4, 105, 2, 1, 1057, 1, 0x000000009000e005ULL},
    {0x20, 4, 105, 2, 1, 1078, 0, 0x00000000000307f2ULL},
    {0x20, 6, 105, 2, 1, 1104, 0, 0x000000009000e001ULL},
    {0x20, 6, 105, 2, 1, 1123, 0, 0x00000000000307f6ULL},
    {0x20, 8, 105, 2, 1, 1147, 0, 0x000000009000e001ULL},
    {0x20, 8, 105, 2, 1, 1172, 0, 0x00000000000307f2ULL},
    {0x20, 8, 105, 2, 1, 1202, 0, 0x0000000000000004ULL},
    {0x20, 10, 105, 2, 1, 1228, 0, 0x000000001000e001ULL},
    {0x20, 10, 105, 2, 1, 1252, 0, 0x00000000800307f2ULL},
    {0x20, 10, 105, 2, 1, 1275, 0, 0x0000000000000004ULL},
    {0x20, 12, 105, 2, 2, 1300, 0, 0x000000009003e7f7ULL},
    {0x20, 12, 405, 2, 1, 1314, 0, 0x000000009003e7f7ULL},
    {0x20, 14, 105, 2, 2, 1331, 0, 0x000000001003e7f7ULL},
    {0x20, 14, 405, 2, 1, 1344, 0, 0x000000001003e7e7ULL},
    {0x20, 14, 405, 2, -1, 1344, 0, 0x0000000000000010ULL},
    {0x20, 14, 105, 2, 2, 1360, 0, 0x0000000080000000ULL},
    {0x20, 14, 405, 2, 1, 1369, 0, 0x0000000080000000ULL},
    {0x21, 0, 105, 2, -1, 1381, 1, 0x000000009003e7f7ULL},
    {0x21, 2, 105, 2, -1, 1405, 0, 0x000000009003e7f7ULL},
    {0x21, 4, 105, 2, 1, 1431, 0, 0x000000009003e7f7ULL},
    {0x21, 6, 105, 2, 1, 1445, 0, 0x000000009003e7e3ULL},
    {0x21, 6, 152, 2, 1, 1445, 0, 0x0000000000000004ULL},
    {0x21, 6, 105, 2, 1, 1460, 0, 0x0000000000000010ULL},
    {0x21, 8, 105, 2, 1, 1478, 0, 0x000000009003e7e3ULL},
    {0x21, 8, 152, 2, 1, 1478, 0, 0x0000000000000004ULL},
    {0x21, 8, 105, 2, 1, 1493, 0, 0x0000000000000010ULL},
    {0x21, 10, 105, 2, 1, 1512, 0, 0x000000009003e7f3ULL},
    {0x21, 10, 152, 2, 1, 1512, 0, 0x0000000000000004ULL},
    {0x21, 12, 105, 2, 1, 1542, 0, 0x0000000000000010ULL},
    {0x21, 12, 105, 2, 1, 1565, 0, 0x0000000000000600ULL},
    {0x21, 15, 105, 1, -1, 800, 0, 0x0000000000000010ULL},
    {0x21, 16, 105, 1, -1, 800, 0, 0x0000000000000010ULL},
    {0x21, 17, 105, 1, -1, 800, 0, 0x0000000000000010ULL},
    {0x21, 18, 105, 1, -1, 800, 0, 0x0000000000000010ULL},
    {0x30, 0, 152, 1, -1, 1592, 1, 0x000000009003e7f7ULL},
    {0x30, 0, 304, 1, -1, 1612, 0, 0x0000000000000004ULL},
    {0x30, 0, 303, 1, -1, 1629, 0, 0x0000000000000004ULL},
    {0x30, 1, 211, 1, -1, 1646, 0, 0x000000009003c7f3ULL},
    {0x30, 1, 211, 1, -1, 1659, 0, 0x0000000000000004ULL},
    {0x30, 1, 211, 1, -1, 1679, 0, 0x0000000000002000ULL},
    {0x30, 2, 211, 1, -1, 1694, 0, 0x000000009003e7f7ULL},
    {0x30, 3, 151, 2, -1, 1707, 0, 0x000000009003e7f7ULL},
    {0x30, 5, 151, 2, -1, 1731, 0, 0x000000009003e7f7ULL},
    {0x30, 7, 151, 2, -1, 1755, 0, 0x000000009003e7e7ULL},
    {0x30, 7, 307, 1, -1, 1779, 0, 0x0000000000000010ULL},
    {0x30, 7, 306, 1, -1, 1793, 0, 0x0000000000000010ULL},
    {0x30, 7, 305, 1, -1, 1807, 0, 0x0000000000000010ULL},
    {0x30, 7, 304, 1, -1, 1821, 0, 0x0000000000000010ULL},
    {0x30, 7, 303, 1, -1, 1835, 0, 0x0000000000000010ULL},
    {0x30, 7, 302, 1, -1, 1849, 0, 0x0000000000000010ULL},
    {0x30, 7, 301, 1, -1, 1863, 0, 0x0000000000000010ULL},
    {0x30, 7, 300, 1, -1, 1877, 0, 0x0000000000000010ULL},
    {0x30, 8, 307, 1, -1, 1891, 0, 0x0000000000000010ULL},
    {0x30, 9, 151, 2, -1, 1909, 0, 0x000000009003e7e7ULL},
    {0x30, 9, 307, 1, 1, 1933, 0, 0x0000000000000010ULL},
    {0x30, 9, 306, 1, 1, 1960, 0, 0x0000000000000010ULL},
    {0x30, 10, 112, 1, 1, 1982, 0, 0x0000000000000010ULL},
    {0x30, 11, 307, 1, -1, 2006, 0, 0x000000009003c7e7ULL},
    {0x30, 11, 112, 1, 1, 2018, 0, 0x0000000000000010ULL},
    {0x30, 11, 307, 1, -1, 1779, 0, 0x0000000000002000ULL},
    {0x30, 12, 307, 1, -1, 1891, 0, 0x000000009003e7e7ULL},
    {0x30, 13, 307, 1, -1, 2077, 0, 0x000000001000e001ULL},
    {0x30, 13, 306, 1, -1, 2081, 0, 0x000000001000e001ULL},
    {0x30, 13, 305, 1, -1, 2103, 0, 0x000000001003e7e7ULL},
    {0x30, 13, 307, 1, -1, 2107, 0, 0x00000000000307e2ULL},
    {0x30, 13, 306, 1, -1, 2134, 0, 0x00000000000307e2ULL},
    {0x30, 13, 307, 1, -1, 2156, 0, 0x0000000000000004ULL},
    {0x30, 13, 306, 1, -1, 2174, 0, 0x0000000000000004ULL},
    {0x30, 13, 307, 1, -1, 2178, 0, 0x0000000080000000ULL},
    {0x30, 13, 306, 1, -1, 2186, 0, 0x0000000080000000ULL},
    {0x30, 13, 305, 1, -1, 2203, 0, 0x0000000080000000ULL},
    {0x60, 0, 304, 1, -1, 2210, 0, 0x000000009003e7f7ULL},
    {0x60, 1, 152, 1, -1, 2230, 0, 0x000000009003e7f7ULL},
    {0x60, 2, 315, 1, -1, 2250, 1, 0x000000009003e7f7ULL},
    {0x60, 2, 303, 1, -1, 2269, 0, 0x0000000000000003ULL},
    {0x60, 2, 302, 1, -1, 2292, 0, 0x000000009003e7f7ULL},
    {0x60, 2, 301, 1, -1, 2310, 1, 0x000000009003e7f7ULL},
    {0x60, 2, 300, 1, -1, 2322, 1, 0x000000009003e7f7ULL},
    {0x60, 2, 303, 1, -1, 293, 1, 0x000000009003e7f4ULL},
    {0x60, 3, 204, 1, -1, 455, 1, 0x000000009003e7f7ULL},
    {0x60, 4, 152, 1, -1, 2357, 0, 0x000000009003e7f7ULL},
    {0x60, 5, 203, 1, -1, 444, 1, 0x000000009003e7f7ULL},
    {0x60, 6, 219, 1, -1, 2377, 0, 0x000000009003e7f3ULL},
    {0x60, 6, 219, 1, -1, 2395, 0, 0x0000000000000004ULL},
    {0x60, 7, 105, 2, 1, 2416, 1, 0x000000009003e7f7ULL},
    {0x60, 9, 105, 2, 1, 2429, 1, 0x000000009003e7f7ULL},
    {0x60, 11, 307, 1, -1, 2448, 0, 0x000000009003e7f7ULL},
    {0x60, 11, 306, 1, -1, 2466, 0, 0x000000009003e7f7ULL},
    {0x60, 11, 305, 1, -1, 2494, 0, 0x000000009003e7f7ULL},
    {0x60, 11, 304, 1, -1, 2516, 0, 0x000000009003e7f7ULL},
    {0x60, 11, 303, 1, -1, 2546, 0, 0x000000009003e7f7ULL},
    {0x60, 11, 302, 1, -1, 2558, 0, 0x000000001003e7e3ULL},
    {0x60, 11, 301, 1, -1, 2576, 0, 0x000000001003e7e3ULL},
    {0x60, 11, 300, 1, -1, 2594, 0, 0x000000009003e7f7ULL},
    {0x60, 11, 302, 1, -1, 800, 0, 0x0000000080000014ULL},
    {0x60, 11, 301, 1, -1, 800, 0, 0x0000000080000014ULL},
    {0x60, 12, 307, 1, -1, 2613, 0, 0x000000009003e7f7ULL},
    {0x60, 12, 306, 1, -1, 2642, 1, 0x000000009003e7f7ULL},
    {0x60, 12, 305, 1, -1, 2671, 0, 0x000000009003e7f7ULL},
    {0x60, 12, 304, 1, -1, 2675, 0, 0x000000009003e7f7ULL},
    {0x60, 12, 303, 1, -1, 2685, 0, 0x000000009003e7f7ULL},
    {0x60, 12, 302, 1, -1, 2695, 0, 0x000000009003e7f7ULL},
    {0x60, 12, 301, 1, -1, 2721, 1, 0x000000009003e7f7ULL},
    {0x60, 12, 300, 1, -1, 2742, 0, 0x000000009003e7f7ULL},
    {0x60, 13, 152, 1, -1, 2763, 0, 0x000000009003e7f7ULL},
    {0x60, 14, 215, 1, -1, 2782, 0, 0x000000009003e7f7ULL},
    {0x60, 15, 215, 1, -1, 2803, 0, 0x000000009003e7f7ULL},
    {0x60, 16, 152, 1, -1, 2824, 0, 0x000000009003e7f7ULL},
    {0x61, 0, 307, 1, -1, 2210, 0, 0x000000009003e7f7ULL},
    {0x61, 1, 152, 1, -1, 2230, 0, 0x000000009003e7f7ULL},
    {0x61, 2, 105, 2, 1, 2840, 1, 0x000000009003e7d7ULL},
    {0x61, 2, 105, 2, 1, 2877, 0, 0x0000000000000020ULL},
    {0x61, 4, 105, 2, 1, 2906, 1, 0x000000009003e7d7ULL},
    {0x61, 4, 105, 2, 1, 2942, 0, 0x0000000000000020ULL},
    {0x61, 6, 105, 2, 1, 2989, 1, 0x000000009003e7f7ULL},
    {0x61, 8, 105, 2, 1, 3021, 1, 0x000000009003e7f7ULL},
    {0x61, 10, 105, 2, 1, 3044, 1, 0x000000009003e7f7ULL},
    {0x61, 12, 105, 2, 1, 3065, 1, 0x000000009003e7f7ULL},
    {0x61, 13, 105, 2, 1, 3092, 0, 0x0000000000000004ULL},
    {0x61, 14, 105, 2, 1, 3125, 0, 0x0000000000000001ULL},
    {0x61, 14, 105, 2, 1, 3092, 0, 0x000000009003e7f2ULL},
    {0x62, 0, 307, 1, -1, 2210, 0, 0x000000009003e7f7ULL},
    {0x62, 1, 152, 1, -1, 2230, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 307, 1, -1, 3159, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 306, 1, -1, 3173, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 305, 1, -1, 3192, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 304, 1, -1, 3215, 1, 0x000000009003e7f7ULL},
    {0x62, 2, 303, 1, -1, 3246, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 302, 1, -1, 3277, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 301, 1, -1, 800, 0, 0x000000009003e7f7ULL},
    {0x62, 2, 300, 1, -1, 3304, 0, 0x000000009003e7f7ULL},
    {0x62, 3, 105, 2, 1, 3341, 0, 0x000000009003e7f7ULL},
    {0x62, 5, 105, 2, 1, 3359, 1, 0x000000009003e7f7ULL},
    {0x62, 7, 307, 1, -1, 3371, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 306, 1, -1, 3396, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 305, 1, -1, 3421, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 304, 1, -1, 3437, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 303, 1, -1, 3453, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 302, 1, -1, 3477, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 301, 1, -1, 3501, 0, 0x000000009003e7f7ULL},
    {0x62, 7, 300, 1, -1, 3525, 0, 0x000000009003e7f7ULL},
    {0x62, 8, 307, 1, -1, 3549, 0, 0x000000009000a077ULL},
    {0x62, 8, 306, 1, -1, 800, 0, 0x000000009000a077ULL},
    {0x62, 8, 305, 1, -1, 800, 0, 0x000000009000a077ULL},
    {0x62, 8, 304, 1, -1, 3554, 0, 0x000000009003e7f7ULL},
    {0x62, 8, 303, 1, -1, 3565, 0, 0x000000009003e7f7ULL},
    {0x62, 8, 302, 1, -1, 3585, 1, 0x000000009003e7f7ULL},
    {0x62, 8, 301, 1, -1, 3612, 0, 0x000000009003e7f7ULL},
    {0x62, 8, 300, 1, -1, 3625, 0, 0x000000009003e7f7ULL},
    {0x62, 8, 307, 1, -1, 3650, 0, 0x0000000000034780ULL},
    {0x62, 8, 306, 1, -1, 3671, 0, 0x0000000000034780ULL},
    {0x62, 8, 305, 1, -1, 3692, 0, 0x0000000000034780ULL},
    {0x62, 8, 336, 1, -1, 3713, 0, 0x0000000000024780ULL},
    {0x62, 9, 105, 2, -1, 3773, 1, 0x000000009003e7f7ULL},
    {0x62, 11, 105, 1, 2, 3793, 1, 0x00000000800327f7ULL},
    {0x62, 11, 405, 1, 1, 3793, 1, 0x000000001000c000ULL},
    {0x62, 12, 152, 1, -1, 3808, 0, 0x000000009003e7f7ULL},
    {0x62, 13, 152, 1, -1, 3843, 0, 0x000000009003e7f7ULL},
    {0x62, 14, 152, 1, -1, 3873, 0, 0x000000009003e7f7ULL},
    {0x62, 15, 105, 2, 2, 3903, 0, 0x000000009003e7e7ULL},
    {0x62, 15, 405, 2, 1, 3931, 0, 0x000000001000e001ULL},
    {0x62, 15, 152, 2, 2, 3903, 0, 0x0000000000000010ULL},
    {0x63, 0, 307, 1, -1, 2210, 0, 0x000000009003e7f7ULL},
    {0x63, 1, 152, 1, -1, 2230, 0, 0x000000009003e7f7ULL},
    {0x63, 2, 215, 1, -1, 3950, 0, 0x000000009003e7f7ULL},
    {0x63, 3, 215, 1, -1, 3973, 0, 0x000000009003e7f7ULL},
    {0x63, 4, 215, 1, -1, 4000, 0, 0x000000009003e7f7ULL},
    {0x63, 5, 215, 1, -1, 4027, 0, 0x000000009003e7f7ULL},
    {0x63, 6, 215, 1, -1, 4054, 0, 0x000000009003e7f7ULL},
    {0x63, 7, 215, 1, -1, 4078, 0, 0x000000009003e7e3ULL},
    {0x63, 7, 214, 1, -1, 4078, 0, 0x0000000000000014ULL},
    {0x63, 8, 215, 1, -1, 800, 0, 0x000000009000a063ULL},
    {0x63, 8, 105, 2, 1, 4108, 0, 0x0000000000014780ULL},
    {0x63, 8, 105, 2, 1, 4174, 0, 0x0000000000020000ULL},
    {0x63, 9, 215, 1, -1, 800, 0, 0x000000009000a063ULL},
    {0x63, 10, 215, 1, -1, 800, 0, 0x000000009000a063ULL},
    {0x63, 10, 101, 1, -1, 4197, 0, 0x0000000000034780ULL},
    {0x63, 11, 301, 1, -1, 4244, 0, 0x0000000010002001ULL},
    {0x63, 11, 215, 1, -1, 800, 0, 0x0000000080000062ULL},
    {0x63, 11, 101, 1, -1, 4276, 0, 0x0000000000034780ULL},
    {0x63, 12, 300, 1, -1, 4328, 0, 0x000000001000a001ULL},
    {0x63, 12, 215, 1, -1, 800, 0, 0x0000000080000042ULL},
    {0x63, 12, 317, 1, -1, 4360, 0, 0x00000000000347a0ULL},
    {0x63, 12, 323, 1, -1, 4416, 0, 0x0000000000034780ULL},
    {0x63, 12, 305, 1, -1, 4465, 0, 0x0000000000034780ULL},
    {0x63, 12, 304, 1, -1, 4504, 0, 0x0000000000034780ULL},
    {0x63, 12, 303, 1, -1, 4569, 0, 0x0000000000034780ULL},
    {0x63, 12, 302, 1, -1, 4612, 0, 0x0000000000034780ULL},
    {0x63, 12, 301, 1, -1, 4244, 0, 0x0000000000008000ULL},
    {0x63, 13, 311, 1, -1, 4681, 0, 0x000000009000a063ULL},
    {0x63, 13, 152, 1, -1, 4681, 0, 0x0000000000030784ULL},
    {0x63, 14, 161, 1, -1, 4701, 0, 0x000000009003e7e7ULL},
    {0x63, 15, 161, 1, -1, 4737, 0, 0x000000009003e7e7ULL},
    {0x63, 16, 307, 1, -1, 4773, 0, 0x000000009003e7f3ULL},
    {0x63, 16, 161, 1, -1, 4786, 0, 0x000000009003e7e7ULL},
    {0x63, 16, 307, 1, -1, 4822, 0, 0x0000000000000004ULL},
    {0x64, 0, 307, 1, -1, 2210, 0, 0x000000009003e7f3ULL},
    {0x64, 1, 152, 1, -1, 2230, 0, 0x000000009003e7f3ULL},
    {0x64, 2, 316, 1, -1, 4862, 0, 0x000000001003e7f3ULL},
    {0x64, 2, 303, 1, -1, 4878, 0, 0x000000001003e7f3ULL},
    {0x64, 2, 302, 1, -1, 4902, 0, 0x000000001003e7f3ULL},
    {0x64, 2, 301, 1, -1, 4920, 0, 0x000000001003e7f3ULL},
    {0x64, 2, 307, 1, -1, 4940, 0, 0x0000000080000000ULL},
    {0x64, 2, 306, 1, -1, 4977, 0, 0x0000000080000000ULL},
    {0x64, 2, 305, 1, -1, 4985, 0, 0x0000000080000000ULL},
    {0x64, 2, 304, 1, -1, 5001, 0, 0x0000000080000000ULL},
    {0x64, 2, 303, 1, -1, 5022, 0, 0x0000000080000000ULL},
    {0x64, 2, 302, 1, -1, 5053, 0, 0x0000000080000000ULL},
    {0x64, 2, 301, 1, -1, 5062, 0, 0x0000000080000000ULL},
    {0x64, 2, 300, 1, -1, 5072, 0, 0x0000000080000000ULL},
    {0x64, 3, 105, 2, -1, 5092, 0, 0x000000009003e7f3ULL},
    {0x64, 5, 105, 2, 1, 5099, 0, 0x000000009003e7f3ULL},
    {0x64, 7, 105, 2, 1, 5127, 0, 0x000000009003e7f3ULL},
    {0x64, 9, 302, 1, -1, 5053, 0, 0x000000009003e7f3ULL},
    {0x64, 9, 301, 1, -1, 5062, 0, 0x000000009003e7f3ULL},
    {0x64, 10, 118, 2, 1, 5155, 0, 0x000000001003e7f3ULL},
    {0x64, 10, 105, 2, 1, 5155, 0, 0x0000000080000000ULL},
    {0x64, 12, 105, 2, 1, 5173, 0, 0x000000009003e7f7ULL},
    {0x64, 14, 152, 1, 1, 5208, 0, 0x000000009003e7f3ULL},
    {0x64, 14, 152, 1, -1, 5208, 0, 0x0000000000000004ULL},
    {0x64, 15, 152, 1, 1, 5231, 0, 0x000000009003e7f3ULL},
    {0x64, 15, 152, 1, -1, 5231, 0, 0x0000000000000004ULL},
    {0x65, 0, 307, 1, -1, 2210, 0, 0x0000000000034782ULL},
    {0x65, 0, 152, 1, -1, 2230, 0, 0x0000000000000780ULL},
    {0x65, 1, 152, 2, -1, 2230, 0, 0x0000000000030002ULL},
    {0x65, 1, 152, 1, -1, 2230, 0, 0x0000000000004000ULL},
    {0x65, 2, 105, 2, 1, 2018, 0, 0x0000000000034782ULL},
    {0x65, 4, 105, 2, 1, 5254, 0, 0x0000000000034782ULL},
    {0x65, 6, 101, 1, -1, 5309, 0, 0x0000000000014002ULL},
    {0x65, 6, 152, 1, -1, 5309, 0, 0x0000000000020780ULL},
    {0xa0, 0, 119, 2, 1, 5351, 0, 0x000000009003e7e3ULL},
    {0xa0, 2, 119, 2, 1, 5364, 0, 0x000000009003e7e3ULL},
    {0xa0, 4, 119, 2, 1, 5393, 0, 0x000000009003e7e3ULL},
    {0xa0, 6, 119, 2, 2, 1360, 0, 0x000000009003e7e3ULL},
    {0xa0, 8, 151, 2, -1, 1755, 0, 0x000000009003e7e3ULL},
    {0xa0, 10, 152, 1, -1, 5411, 0, 0x000000009003e7e3ULL},
    {0xa0, 11, 152, 1, -1, 5411, 0, 0x000000009003e7e3ULL},
    {0xa0, 12, 307, 1, -1, 5422, 0, 0x000000009003e7e3ULL},
    {0xa0, 12, 306, 1, -1, 5436, 0, 0x000000009003e7e3ULL},
    {0xa0, 12, 305, 1, -1, 1891, 0, 0x000000009003e7e3ULL},
    {0xa0, 12, 304, 1, -1, 5456, 0, 0x000000001003e7e3ULL},
    {0xa0, 12, 303, 1, -1, 2081, 0, 0x000000001000e001ULL},
    {0xa0, 12, 302, 1, -1, 5473, 0, 0x000000001003e7e3ULL},
    {0xa0, 12, 301, 1, -1, 2156, 0, 0x000000009003e7e3ULL},
    {0xa0, 12, 300, 1, -1, 5490, 0, 0x000000009003e7e3ULL},
    {0xa0, 12, 303, 1, -1, 5501, 0, 0x00000000000307e2ULL},
    {0xa0, 12, 301, 1, 1, 2156, 0, 0x0000000000000010ULL},
    {0xa0, 12, 304, 1, -1, 2203, 0, 0x0000000080000000ULL},
    {0xa0, 12, 303, 1, -1, 2186, 0, 0x0000000080000000ULL},
    {0xa0, 12, 302, 1, -1, 2178, 0, 0x0000000080000000ULL},
    {0xa0, 13, 303, 1, -1, 527, 0, 0x000000009003e7e3ULL},
    {0xa0, 13, 302, 1, -1, 5518, 0, 0x000000009003e7e3ULL},
    {0xa0, 13, 301, 1, -1, 5545, 0, 0x000000009003e7e3ULL},
    {0xa0, 13, 300, 1, -1, 5578, 0, 0x000000009003e7e3ULL},
    {0xa0, 14, 105, 2, 1, 5608, 0, 0x000000009003e7e3ULL},
    {0xa1, 0, 119, 2, 1, 5636, 0, 0x000000009003e7f3ULL},
    {0xa1, 2, 119, 2, 1, 5679, 0, 0x000000009003e7f3ULL},
    {0xa1, 4, 302, 1, -1, 5723, 0, 0x000000009003e7e3ULL},
    {0xa1, 4, 301, 1, -1, 5755, 0, 0x000000009003e7f3ULL},
    {0xa1, 4, 300, 1, -1, 3554, 0, 0x000000009003e7f3ULL},
    {0xa1, 5, 114, 2, 1, 5775, 0, 0x000000009003e7e3ULL},
    {0xa1, 7, 114, 2, 1, 5798, 0, 0x000000009003e7e3ULL},
    {0xa1, 9, 305, 1, -1, 5822, 0, 0x000000009003e7e3ULL},
    {0xa1, 9, 304, 1, -1, 5839, 0, 0x000000009003e7e3ULL},
    {0xa1, 9, 303, 1, -1, 5859, 0, 0x000000009003e7e3ULL},
    {0xa1, 9, 302, 1, -1, 5870, 0, 0x000000009003e7e3ULL},
    {0xa1, 9, 301, 1, -1, 5883, 0, 0x000000009003e7e3ULL},
    {0xa1, 9, 300, 1, -1, 5903, 0, 0x000000009003e7e3ULL},
    {0x00, 0, 801, 0, -1, 0, 2, 0x000000006ff80008ULL},
    {0x00, 0, 152, 1, -1, 18, 0, 0x000000006ffc1808ULL},
    {0x00, 0, 802, 0, -1, 0, 2, 0x0000000000041800ULL},
    {0x00, 1, 152, 1, -1, 34, 0, 0x000000006ffc1808ULL},
    {0x00, 2, 152, 1, -1, 53, 0, 0x000000006ffc1808ULL},
    {0x00, 3, 152, 1, -1, 72, 0, 0x000000006ffc1808ULL},
    {0x00, 4, 152, 1, -1, 85, 0, 0x000000006ffc1808ULL},
    {0x00, 5, 152, 1, -1, 110, 0, 0x000000006ffc1808ULL},
    {0x00, 6, 152, 1, -1, 131, 0, 0x000000006ffc1808ULL},
    {0x00, 7, 152, 1, -1, 153, 0, 0x000000006ffc1808ULL},
    {0x00, 8, 152, 1, -1, 172, 0, 0x000000006ffc1808ULL},
    {0x00, 9, 152, 1, -1, 202, 0, 0x000000006ffc1808ULL},
    {0x00, 10, 152, 1, -1, 228, 0, 0x000000006ffc1808ULL},
    {0x00, 11, 152, 1, -1, 244, 0, 0x000000006ffc1808ULL},
    {0x00, 12, 105, 1, -1, 260, 0, 0x000000006ffc1808ULL},
    {0x10, 0, 217, 1, -1, 278, 1, 0x000000006ffc1808ULL},
    {0x10, 1, 307, 1, -1, 293, 1, 0x000000006ffc1808ULL},
    {0x10, 1, 306, 1, -1, 311, 0, 0x000000006ffc1808ULL},
    {0x10, 1, 305, 1, -1, 327, 0, 0x000000006ffc1808ULL},
    {0x10, 1, 304, 1, -1, 343, 1, 0x000000006ffc1808ULL},
    {0x10, 1, 303, 1, -1, 361, 0, 0x000000006ffc1808ULL},
    {0x10, 1, 302, 1, -1, 382, 0, 0x000000006ffc1808ULL},
    {0x10, 1, 301, 1, -1, 412, 0, 0x000000006ffc1808ULL},
    {0x10, 1, 300, 1, -1, 426, 0, 0x000000006ffc1808ULL},
    {0x10, 4, 203, 1, -1, 444, 1, 0x000000006ffc1808ULL},
    {0x10, 5, 204, 1, -1, 455, 1, 0x000000006ffc1808ULL},
    {0x10, 6, 114, 2, 1, 466, 0, 0x000000006ffc1808ULL},
    {0x10, 8, 114, 2, 1, 508, 0, 0x000000006ffc1808ULL},
    {0x10, 10, 307, 1, -1, 527, 0, 0x000000006ffc1808ULL},
    {0x10, 10, 310, 1, -1, 548, 0, 0x000000006ffc1808ULL},
    {0x10, 10, 303, 1, -1, 585, 0, 0x000000006ffc1808ULL},
    {0x10, 10, 311, 1, -1, 608, 0, 0x000000006ffc1808ULL},
    {0x10, 11, 307, 1, -1, 647, 0, 0x000000006ffc1808ULL},
    {0x10, 11, 310, 1, -1, 663, 0, 0x000000006ffc1808ULL},
    {0x10, 11, 303, 1, -1, 687, 0, 0x000000006ffc1808ULL},
    {0x10, 11, 311, 1, -1, 703, 0, 0x000000006ffc1808ULL},
    {0x10, 12, 307, 1, -1, 727, 0, 0x000000006ffc1808ULL},
    {0x10, 12, 310, 1, -1, 750, 0, 0x000000006ffc1808ULL},
    {0x10, 12, 303, 1, -1, 781, 0, 0x000000006ffc1808ULL},
    {0x10, 12, 311, 1, -1, 800, 0, 0x000000006ffc1808ULL},
    {0x11, 0, 215, 1, -1, 811, 0, 0x000000006ffc1808ULL},
    {0x11, 1, 215, 1, -1, 834, 0, 0x000000006ffc1808ULL},
    {0x11, 2, 215, 1, -1, 861, 0, 0x000000006ffc1808ULL},
    {0x11, 3, 215, 1, -1, 888, 0, 0x000000006ffc1808ULL},
    {0x11, 4, 215, 1, -1, 915, 0, 0x000000006ffc1808ULL},
    {0x11, 5, 214, 1, -1, 939, 0, 0x000000006ffc1808ULL},
    {0x20, 0, 105, 2, 1, 963, 1, 0x000000006ff41808ULL},
    {0x20, 0, 105, 2, 1, 5922, 1, 0x0000000000080000ULL},
    {0x20, 2, 105, 2, 1, 1032, 0, 0x0000000000000008ULL},
    {0x20, 2, 105, 2, 1, 985, 0, 0x000000002efc1800ULL},
    {0x20, 2, 105, 2, 1, 5364, 0, 0x0000000041000000ULL},
    {0x20, 4, 105, 2, 1, 1057, 1, 0x000000006ffc1808ULL},
    {0x20, 6, 105, 2, 1, 1123, 0, 0x0000000000000008ULL},
    {0x20, 6, 105, 2, 1, 1104, 0, 0x000000002efc1800ULL},
    {0x20, 6, 105, 2, 1, 5940, 0, 0x0000000041000000ULL},
    {0x20, 8, 105, 2, 1, 1202, 0, 0x0000000000000008ULL},
    {0x20, 8, 105, 2, 1, 1147, 0, 0x000000002ef41800ULL},
    {0x20, 8, 105, 2, 1, 5965, 0, 0x0000000000080000ULL},
    {0x20, 8, 105, 2, 1, 5990, 0, 0x0000000041000000ULL},
    {0x20, 10, 105, 2, 1, 1275, 0, 0x0000000000000008ULL},
    {0x20, 10, 105, 2, 1, 1252, 0, 0x000000002ef41800ULL},
    {0x20, 10, 105, 2, 1, 5393, 0, 0x0000000041080000ULL},
    {0x20, 12, 105, 2, 1, 6023, 0, 0x0000000000000008ULL},
    {0x20, 12, 105, 2, 1, 6045, 0, 0x000000002ef41800ULL},
    {0x20, 12, 105, 2, 1, 1431, 0, 0x0000000000080000ULL},
    {0x20, 12, 105, 2, 1, 6061, 0, 0x0000000041000000ULL},
    {0x20, 14, 105, 2, 2, 1360, 0, 0x000000006ff80008ULL},
    {0x20, 14, 405, 2, 1, 1369, 0, 0x000000006ff80008ULL},
    {0x20, 14, 105, 2, 2, 6071, 0, 0x0000000000041800ULL},
    {0x20, 14, 405, 2, 1, 3931, 0, 0x0000000000041800ULL},
    {0x20, 16, 105, 2, -1, 800, 0, 0x0000000022a80008ULL},
    {0x20, 18, 105, 2, -1, 800, 0, 0x0000000022a80008ULL},
    {0x21, 0, 105, 2, -1, 1381, 1, 0x000000006ffc1808ULL},
    {0x21, 0, 105, 2, -1, 1405, 0, 0x0000000041000000ULL},
    {0x21, 2, 105, 2, -1, 1405, 0, 0x000000002efc1808ULL},
    {0x21, 2, 101, 2, -1, 6087, 1, 0x0000000041000000ULL},
    {0x21, 4, 101, 2, -1, 6087, 1, 0x000000002ef41808ULL},
    {0x21, 4, 101, 2, -1, 6109, 0, 0x0000000000080000ULL},
    {0x21, 4, 105, 2, 1, 1460, 0, 0x0000000041000000ULL},
    {0x21, 6, 307, 1, -1, 6121, 0, 0x000000002efc1808ULL},
    {0x21, 6, 306, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 305, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 304, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 303, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 302, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 301, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 300, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 6, 105, 2, 1, 1493, 0, 0x0000000041000000ULL},
    {0x21, 7, 105, 2, 1, 1460, 1, 0x0000000000000008ULL},
    {0x21, 7, 105, 2, 1, 1460, 0, 0x000000002efc1800ULL},
    {0x21, 8, 105, 2, 1, 6139, 0, 0x0000000041000000ULL},
    {0x21, 9, 105, 2, 1, 1493, 1, 0x0000000000000008ULL},
    {0x21, 9, 105, 2, 1, 1493, 0, 0x000000002efc1800ULL},
    {0x21, 10, 105, 2, 1, 1542, 0, 0x0000000041000000ULL},
    {0x21, 11, 105, 2, 1, 6139, 0, 0x000000002efc1808ULL},
    {0x21, 13, 105, 2, 1, 1542, 0, 0x000000002efc1808ULL},
    {0x21, 15, 105, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 16, 105, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 17, 105, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x21, 18, 105, 1, -1, 800, 0, 0x000000002efc1808ULL},
    {0x30, 0, 152, 1, -1, 1592, 1, 0x000000006ffc1808ULL},
    {0x30, 0, 307, 1, -1, 6162, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 306, 1, -1, 6179, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 211, 1, -1, 1646, 0, 0x000000006dd00008ULL},
    {0x30, 0, 151, 2, -1, 6196, 0, 0x000000004d541808ULL},
    {0x30, 0, 307, 1, -1, 2006, 0, 0x0000000041000008ULL},
    {0x30, 0, 306, 1, -1, 1793, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 305, 1, -1, 1807, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 304, 1, -1, 1821, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 303, 1, -1, 1835, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 307, 1, -1, 1891, 0, 0x0000000041000008ULL},
    {0x30, 0, 306, 1, -1, 6218, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 305, 1, -1, 6238, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 304, 1, -1, 6258, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 307, 1, -1, 6278, 0, 0x0000000000000008ULL},
    {0x30, 0, 306, 1, -1, 6291, 0, 0x0000000000080008ULL},
    {0x30, 0, 305, 1, -1, 5456, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 304, 1, -1, 1612, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 303, 1, -1, 1629, 0, 0x000000006ddc1808ULL},
    {0x30, 0, 211, 1, -1, 1679, 0, 0x00000000000c1800ULL},
    {0x30, 0, 307, 1, -1, 6300, 0, 0x000000002cdc1800ULL},
    {0x30, 0, 307, 1, -1, 5473, 0, 0x000000004d5c1800ULL},
    {0x30, 0, 306, 1, -1, 5501, 0, 0x000000004d541800ULL},
    {0x30, 0, 151, 2, -1, 1707, 0, 0x0000000020880000ULL},
    {0x30, 0, 307, 1, -1, 1779, 0, 0x000000002cd80000ULL},
    {0x30, 0, 303, 1, -1, 6320, 0, 0x0000000000080000ULL},
    {0x30, 0, 307, 1, -1, 6340, 0, 0x0000000020800000ULL},
    {0x30, 0, 306, 1, -1, 6354, 0, 0x0000000020800000ULL},
    {0x30, 1, 152, 1, -1, 6364, 0, 0x000000006ddc1808ULL},
    {0x30, 1, 211, 1, -1, 1694, 0, 0x000000006ddc1808ULL},
    {0x30, 1, 211, 1, -1, 1646, 0, 0x0000000002200000ULL},
    {0x30, 2, 151, 2, -1, 1731, 0, 0x000000006ddc1808ULL},
    {0x30, 2, 211, 1, -1, 1694, 0, 0x0000000002200000ULL},
    {0x30, 3, 151, 2, -1, 1707, 0, 0x0000000002200000ULL},
    {0x30, 4, 151, 2, -1, 1755, 0, 0x000000006ddc1808ULL},
    {0x30, 5, 151, 2, -1, 1731, 0, 0x0000000002200000ULL},
    {0x30, 6, 151, 2, -1, 1909, 0, 0x000000006ddc1808ULL},
    {0x30, 7, 307, 1, -1, 1779, 0, 0x0000000002241800ULL},
    {0x30, 7, 306, 1, -1, 1793, 0, 0x0000000002200000ULL},
    {0x30, 7, 305, 1, -1, 1807, 0, 0x0000000002200000ULL},
    {0x30, 7, 304, 1, -1, 1821, 0, 0x0000000002200000ULL},
    {0x30, 7, 303, 1, -1, 1835, 0, 0x0000000002200000ULL},
    {0x30, 8, 151, 2, -1, 6386, 0, 0x000000006ddc1808ULL},
    {0x30, 8, 307, 1, -1, 6300, 0, 0x0000000002200000ULL},
    {0x30, 8, 306, 1, -1, 6218, 0, 0x0000000002200000ULL},
    {0x30, 8, 305, 1, -1, 6238, 0, 0x0000000002200000ULL},
    {0x30, 8, 304, 1, -1, 6258, 0, 0x0000000002200000ULL},
    {0x30, 9, 307, 1, -1, 6340, 0, 0x0000000002200000ULL},
    {0x30, 9, 306, 1, -1, 6354, 0, 0x0000000002200000ULL},
    {0x30, 9, 305, 1, -1, 5456, 0, 0x0000000002200000ULL},
    {0x30, 9, 304, 1, -1, 1612, 0, 0x0000000002200000ULL},
    {0x30, 9, 303, 1, -1, 1629, 0, 0x0000000002200000ULL},
    {0x60, 0, 304, 1, -1, 2210, 0, 0x000000006ffc1808ULL},
    {0x60, 1, 152, 1, -1, 2230, 0, 0x000000006ffc1808ULL},
    {0x60, 2, 315, 1, -1, 2250, 1, 0x000000006ffc1808ULL},
    {0x60, 2, 303, 1, -1, 293, 1, 0x000000006ffc1808ULL},
    {0x60, 2, 302, 1, -1, 2292, 0, 0x000000006ffc1808ULL},
    {0x60, 2, 301, 1, -1, 2310, 1, 0x000000006ffc1808ULL},
    {0x60, 2, 300, 1, -1, 2322, 1, 0x000000006ffc1808ULL},
    {0x60, 3, 204, 1, -1, 455, 1, 0x000000006ffc1808ULL},
    {0x60, 4, 314, 2, -1, 6410, 0, 0x0000000063a80008ULL},
    {0x60, 4, 152, 1, -1, 2357, 0, 0x0000000000541800ULL},
    {0x60, 4, 152, 2, -1, 6410, 0, 0x000000000c000000ULL},
    {0x60, 5, 203, 1, -1, 444, 1, 0x0000000000541800ULL},
    {0x60, 6, 219, 1, -1, 2377, 0, 0x000000006ffc1808ULL},
    {0x60, 7, 105, 2, 1, 2416, 1, 0x000000006ffc1808ULL},
    {0x60, 9, 105, 2, 1, 2429, 1, 0x000000006ffc1808ULL},
    {0x60, 11, 307, 1, -1, 2448, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 306, 1, -1, 2466, 0, 0x000000004d5c1808ULL},
    {0x60, 11, 305, 1, -1, 2494, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 304, 1, -1, 2516, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 303, 1, -1, 2546, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 302, 1, -1, 800, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 301, 1, -1, 800, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 300, 1, -1, 2594, 0, 0x000000006ffc1808ULL},
    {0x60, 11, 306, 1, -1, 6427, 0, 0x0000000022a00000ULL},
    {0x60, 12, 307, 1, -1, 2613, 0, 0x000000006ffc1808ULL},
    {0x60, 12, 306, 1, -1, 2642, 1, 0x000000006ffc1808ULL},
    {0x60, 12, 305, 1, -1, 2671, 0, 0x000000006ffc1808ULL},
    {0x60, 12, 304, 1, -1, 2675, 0, 0x000000006ffc1808ULL},
    {0x60, 12, 303, 1, -1, 2685, 0, 0x000000006ffc1808ULL},
    {0x60, 12, 302, 1, -1, 6449, 0, 0x0000000022fc1808ULL},
    {0x60, 12, 301, 1, -1, 2721, 1, 0x000000006ffc1808ULL},
    {0x60, 12, 300, 1, -1, 2742, 0, 0x000000006ffc1808ULL},
    {0x60, 12, 302, 1, -1, 2695, 0, 0x000000004d000000ULL},
    {0x60, 13, 152, 1, -1, 2763, 0, 0x000000006ffc1808ULL},
    {0x60, 14, 215, 1, -1, 2782, 0, 0x000000006ffc1808ULL},
    {0x60, 15, 215, 1, -1, 2803, 0, 0x000000006ffc1808ULL},
    {0x60, 16, 152, 1, -1, 2824, 0, 0x000000006ffc1808ULL},
    {0x61, 0, 307, 1, -1, 2210, 0, 0x000000006ffc1808ULL},
    {0x61, 1, 152, 1, -1, 2230, 0, 0x000000006ffc1808ULL},
    {0x61, 2, 105, 2, 1, 2840, 1, 0x000000002ef41008ULL},
    {0x61, 2, 105, 2, 1, 2877, 0, 0x0000000000000800ULL},
    {0x61, 2, 105, 2, 1, 6453, 0, 0x0000000041080000ULL},
    {0x61, 4, 105, 2, 1, 2906, 1, 0x000000002ef41008ULL},
    {0x61, 4, 105, 2, 1, 2942, 0, 0x0000000000000800ULL},
    {0x61, 4, 105, 2, 1, 6489, 0, 0x0000000041080000ULL},
    {0x61, 6, 105, 2, 1, 2989, 1, 0x000000006ffc1808ULL},
    {0x61, 8, 105, 2, 1, 3021, 1, 0x000000006ffc1008ULL},
    {0x61, 8, 105, 2, 1, 6518, 0, 0x0000000000000800ULL},
    {0x61, 10, 105, 2, 1, 3044, 1, 0x000000006ffc1808ULL},
    {0x61, 12, 105, 2, 1, 3065, 1, 0x000000006ff41808ULL},
    {0x61, 12, 105, 2, 1, 6546, 0, 0x0000000000080000ULL},
    {0x61, 13, 105, 2, 1, 3092, 0, 0x0000000000000008ULL},
    {0x61, 14, 105, 2, 1, 3092, 0, 0x000000002ef41800ULL},
    {0x61, 14, 105, 2, 1, 6555, 0, 0x0000000000080000ULL},
    {0x62, 0, 307, 1, -1, 2210, 0, 0x000000006ffc1808ULL},
    {0x62, 1, 152, 1, -1, 2230, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 307, 1, -1, 3159, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 306, 1, -1, 3173, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 305, 1, -1, 3192, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 304, 1, -1, 3215, 1, 0x000000006ffc1808ULL},
    {0x62, 2, 303, 1, -1, 3246, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 302, 1, -1, 3277, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 301, 1, -1, 800, 0, 0x000000006ffc1808ULL},
    {0x62, 2, 300, 1, -1, 3304, 0, 0x000000006ffc1808ULL},
    {0x62, 3, 105, 2, 1, 3341, 0, 0x000000006ffc1808ULL},
    {0x62, 5, 105, 2, 1, 3359, 1, 0x000000006ffc1808ULL},
    {0x62, 7, 307, 1, -1, 3371, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 306, 1, -1, 3396, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 305, 1, -1, 3421, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 304, 1, -1, 3437, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 303, 1, -1, 3453, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 302, 1, -1, 3477, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 301, 1, -1, 3501, 0, 0x000000006ffc1808ULL},
    {0x62, 7, 300, 1, -1, 3525, 0, 0x000000006ffc1808ULL},
    {0x62, 8, 307, 1, -1, 3549, 0, 0x000000006ffc1808ULL},
    {0x62, 8, 306, 1, -1, 800, 0, 0x0000000063fc1808ULL},
    {0x62, 8, 305, 1, -1, 800, 0, 0x0000000063fc1808ULL},
    {0x62, 8, 304, 1, -1, 800, 0, 0x0000000063fc1808ULL},
    {0x62, 8, 303, 1, -1, 800, 0, 0x0000000000000008ULL},
    {0x62, 8, 302, 1, -1, 3585, 1, 0x000000006ffc1808ULL},
    {0x62, 8, 301, 1, -1, 3612, 0, 0x000000006ffc1808ULL},
    {0x62, 8, 300, 1, -1, 3625, 0, 0x000000006ff41808ULL},
    {0x62, 8, 303, 1, -1, 3565, 0, 0x0000000063fc1800ULL},
    {0x62, 8, 300, 1, -1, 6585, 0, 0x0000000000080000ULL},
    {0x62, 8, 306, 1, -1, 6606, 0, 0x000000000c000000ULL},
    {0x62, 8, 305, 1, -1, 4985, 0, 0x000000000c000000ULL},
    {0x62, 8, 304, 1, -1, 5001, 0, 0x000000000c000000ULL},
    {0x62, 8, 303, 1, -1, 6633, 0, 0x000000000c000000ULL},
    {0x62, 9, 105, 2, -1, 3773, 1, 0x000000006ffc1808ULL},
    {0x62, 11, 105, 1, 2, 3793, 1, 0x000000006ffc1808ULL},
    {0x62, 12, 152, 1, -1, 3808, 0, 0x000000006ffc1808ULL},
    {0x62, 13, 152, 1, -1, 3843, 0, 0x0000000063fc1808ULL},
    {0x62, 13, 152, 1, -1, 6647, 0, 0x000000000c000000ULL},
    {0x62, 14, 152, 1, -1, 3873, 0, 0x0000000063fc1808ULL},
    {0x62, 14, 152, 1, -1, 6668, 0, 0x000000000c000000ULL},
    {0x62, 15, 152, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 15, 105, 2, 2, 3903, 0, 0x0000000000041800ULL},
    {0x62, 15, 405, 2, 1, 3931, 0, 0x0000000000041800ULL},
    {0x62, 16, 307, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 306, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 305, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 304, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 303, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 302, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 301, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x62, 16, 300, 1, -1, 800, 0, 0x000000006ff80008ULL},
    {0x63, 0, 307, 1, -1, 2210, 0, 0x000000006ffc1808ULL},
    {0x63, 1, 152, 1, -1, 2230, 0, 0x000000006ffc1808ULL},
    {0x63, 2, 215, 1, -1, 3950, 0, 0x000000006ffc1808ULL},
    {0x63, 3, 215, 1, -1, 3973, 0, 0x000000006ffc1808ULL},
    {0x63, 4, 215, 1, -1, 4000, 0, 0x000000006ffc1808ULL},
    {0x63, 5, 215, 1, -1, 4027, 0, 0x000000006ffc1808ULL},
    {0x63, 6, 215, 1, -1, 4054, 0, 0x000000006ffc1808ULL},
    {0x63, 7, 214, 1, -1, 4078, 0, 0x000000006ffc1808ULL},
    {0x64, 0, 307, 1, -1, 2210, 0, 0x000000006ffc1808ULL},
    {0x64, 1, 152, 1, -1, 2230, 0, 0x000000006ffc1808ULL},
    {0x64, 2, 316, 1, -1, 4862, 0, 0x000000006ffc1808ULL},
    {0x64, 2, 303, 1, -1, 4878, 0, 0x000000006ffc1808ULL},
    {0x64, 2, 302, 1, -1, 4902, 0, 0x000000006ffc1808ULL},
    {0x64, 2, 301, 1, -1, 4920, 0, 0x000000006ffc1808ULL},
    {0x64, 2, 300, 1, -1, 6689, 0, 0x0000000008080000ULL},
    {0x64, 3, 105, 2, -1, 5092, 0, 0x000000006ffc1808ULL},
    {0x64, 5, 105, 2, 1, 5099, 0, 0x000000006ffc1808ULL},
    {0x64, 7, 105, 2, 1, 5127, 0, 0x000000006ffc1808ULL},
    {0x64, 9, 302, 1, -1, 5053, 0, 0x000000000c541800ULL},
    {0x64, 9, 301, 1, -1, 5062, 0, 0x000000000c541800ULL},
    {0x64, 9, 301, 1, -1, 5053, 0, 0x0000000022a00000ULL},
    {0x64, 9, 300, 1, -1, 5062, 0, 0x0000000022a00000ULL},
    {0x64, 10, 118, 2, 1, 5155, 0, 0x0000000000041800ULL},
    {0x64, 10, 118, 2, 1, 4174, 0, 0x000000002ef00000ULL},
    {0x64, 12, 105, 2, 1, 5173, 0, 0x0000000000041800ULL},
    {0x64, 14, 152, 1, 1, 5208, 0, 0x0000000000041800ULL},
    {0x64, 15, 152, 1, 1, 5231, 0, 0x0000000000041800ULL},
    {0x50, 0, 103, 2, -1, 6715, 1, 0x0000000100000000ULL},
    {0x50, 2, 103, 2, -1, 6732, 1, 0x0000000100000000ULL},
    {0x53, 0, 152, 2, -1, 6749, 1, 0x0000000100000000ULL},
    {0x53, 2, 164, 1, -1, 6758, 1, 0x0000000100000000ULL},
    {0x53, 3, 164, 1, -1, 6783, 1, 0x0000000100000000ULL},
    {0x53, 4, 200, 1, -1, 6808, 1, 0x0000000100000000ULL},
    {0x53, 5, 200, 1, -1, 6832, 1, 0x0000000100000000ULL},
    {0x53, 6, 200, 1, -1, 5490, 1, 0x0000000100000000ULL},
    {0x53, 7, 200, 1, -1, 6846, 1, 0x0000000100000000ULL},
    {0x53, 8, 200, 1, -1, 6865, 1, 0x0000000100000000ULL},
    {0x53, 10, 200, 1, -1, 6881, 1, 0x0000000100000000ULL},
    {0x53, 11, 200, 1, -1, 6898, 1, 0x0000000100000000ULL},
    {0x54, 0, 103, 2, -1, 6914, 1, 0x0000000100000000ULL},
    {0x54, 2, 103, 2, -1, 6942, 1, 0x0000000100000000ULL},
    {0x54, 4, 103, 2, -1, 6973, 1, 0x0000000100000000ULL},
    {0x54, 6, 103, 2, -1, 6994, 1, 0x0000000100000000ULL},
    {0x54, 8, 109, 2, -1, 7026, 1, 0x0000000100000000ULL},
    {0x54, 10, 103, 2, -1, 7050, 1, 0x0000000100000000ULL},
    {0x54, 12, 312, 1, -1, 7063, 1, 0x0000000100000000ULL},
    {0x54, 13, 151, 1, -1, 7077, 1, 0x0000000100000000ULL},
    {0x55, 0, 201, 1, -1, 278, 1, 0x0000000100000000ULL},
    {0x55, 1, 204, 1, -1, 455, 1, 0x0000000100000000ULL},
    {0x55, 2, 204, 1, -1, 7093, 1, 0x0000000100000000ULL},
    {0x55, 3, 204, 1, -1, 7110, 1, 0x0000000100000000ULL},
    {0x55, 4, 204, 1, -1, 7123, 1, 0x0000000100000000ULL},
    {0x53, 0, 200, 1, -1, 7136, 1, 0x0000000200000000ULL},
    {0x53, 3, 200, 1, -1, 7153, 1, 0x0000000200000000ULL},
    {0x53, 5, 200, 1, -1, 7170, 1, 0x0000000200000000ULL},
    {0x53, 6, 200, 1, -1, 7197, 1, 0x0000000200000000ULL},
    {0x54, 0, 153, 2, -1, 7225, 1, 0x0000000200000000ULL},
    {0x54, 2, 153, 2, -1, 7254, 1, 0x0000000200000000ULL},
    {0x54, 4, 153, 2, -1, 7275, 1, 0x0000000200000000ULL},
    {0x54, 6, 153, 2, -1, 7297, 1, 0x0000000200000000ULL},
    {0x54, 8, 153, 2, -1, 7302, 1, 0x0000000200000000ULL},
    {0x54, 10, 103, 2, -1, 7320, 1, 0x0000000200000000ULL},
    {0x54, 12, 101, 1, -1, 7063, 1, 0x0000000200000000ULL},
    {0x54, 13, 151, 1, -1, 7077, 1, 0x0000000200000000ULL},
    {0x55, 0, 201, 1, -1, 278, 1, 0x0000000200000000ULL},
    {0x55, 1, 204, 1, -1, 455, 1, 0x0000000200000000ULL},
    {0x55, 2, 204, 1, -1, 7093, 1, 0x0000000200000000ULL},
    {0x55, 3, 204, 1, -1, 7110, 1, 0x0000000200000000ULL},
    {0x55, 4, 204, 1, -1, 7123, 1, 0x0000000200000000ULL},
    {0x56, 0, 103, 2, -1, 7325, 1, 0x0000000200000000ULL},
};

// Known identification keys (data/fingerprints.json): a survey key starting with key is that model
#define CATALOG_FINGERPRINT_COUNT 0
static const CatalogFingerprint CATALOG_FINGERPRINTS[CATALOG_FINGERPRINT_COUNT + 1] = {
    {nullptr, -1},
};

// Indoor unit AS numbers (data/as_numbers.json, known indoor unit boards, 2026-09): body, suffix digits (0xFF = any), candidates
#define CATALOG_AS_COUNT 229
static const CatalogAsNumber CATALOG_AS[CATALOG_AS_COUNT + 1] = {
    {1008467, 0x01, 0xff, 0x0000000000040000ULL},
    {1008467, 0xff, 0xff, 0x0000000000040000ULL},
    {1008468, 0x01, 0xff, 0x0000000000040000ULL},
    {1008468, 0xff, 0xff, 0x0000000000040000ULL},
    {1705393, 0x01, 0xff, 0x0000000000300000ULL},
    {1705393, 0xff, 0xff, 0x0000000000300000ULL},
    {1706407, 0x01, 0xff, 0x0000000000080000ULL},
    {1706407, 0xff, 0xff, 0x0000000000080000ULL},
    {1706408, 0x01, 0xff, 0x0000000000000008ULL},
    {1706408, 0xff, 0xff, 0x0000000000000008ULL},
    {1706409, 0x01, 0xff, 0x0000000000100000ULL},
    {1706409, 0x02, 0x01, 0x0000000000200000ULL},
    {1706409, 0x02, 0x02, 0x0000000000200000ULL},
    {1706409, 0x02, 0x03, 0x0000000000200000ULL},
    {1706409, 0x02, 0x04, 0x0000000000200000ULL},
    {1706409, 0x02, 0x05, 0x0000000000100000ULL},
    {1706409, 0x02, 0x06, 0x0000000000100000ULL},
    {1706409, 0x02, 0x07, 0x0000000000100000ULL},
    {1706409, 0x02, 0x08, 0x0000000000100000ULL},
    {1706409, 0x02, 0x09, 0x0000000000100000ULL},
    {1706409, 0x02, 0xff, 0x0000000000300000ULL},
    {1706409, 0x03, 0x00, 0x0000000000100000ULL},
    {1706409, 0x03, 0x05, 0x0000000000200000ULL},
    {1706409, 0x03, 0x06, 0x0000000000200000ULL},
    {1706409, 0x03, 0x07, 0x0000000000200000ULL},
    {1706409, 0x03, 0x08, 0x0000000000200000ULL},
    {1706409, 0x03, 0xff, 0x0000000000300000ULL},
    {1706409, 0xff, 0xff, 0x0000000000300000ULL},
    {1706432, 0x01, 0x01, 0x0000000000100000ULL},
    {1706432, 0x01, 0x02, 0x0000000000100000ULL},
    {1706432, 0x01, 0x03, 0x0000000000100000ULL},
    {1706432, 0x01, 0x04, 0x0000000000100000ULL},
    {1706432, 0x01, 0x05, 0x0000000000100000ULL},
    {1706432, 0x01, 0x06, 0x0000000000100000ULL},
    {1706432, 0x01, 0x07, 0x0000000000200000ULL},
    {1706432, 0x01, 0x08, 0x0000000000200000ULL},
    {1706432, 0x01, 0x09, 0x0000000000200000ULL},
    {1706432, 0x01, 0xff, 0x0000000000300000ULL},
    {1706432, 0x02, 0x00, 0x0000000000200000ULL},
    {1706432, 0x02, 0x01, 0x0000000000200000ULL},
    {1706432, 0x02, 0x02, 0x0000000000200000ULL},
    {1706432, 0x02, 0x03, 0x0000000000200000ULL},
    {1706432, 0x02, 0x04, 0x0000000000200000ULL},
    {1706432, 0x02, 0x05, 0x0000000000100000ULL},
    {1706432, 0x02, 0x06, 0x0000000000100000ULL},
    {1706432, 0x02, 0x07, 0x0000000000100000ULL},
    {1706432, 0x02, 0x08, 0x0000000000100000ULL},
    {1706432, 0x02, 0x09, 0x0000000000100000ULL},
    {1706432, 0x02, 0xff, 0x0000000000300000ULL},
    {1706432, 0x03, 0x00, 0x0000000000100000ULL},
    {1706432, 0x03, 0x01, 0x0000000000200000ULL},
    {1706432, 0x03, 0x02, 0x0000000000200000ULL},
    {1706432, 0x03, 0x03, 0x0000000000200000ULL},
    {1706432, 0x03, 0x04, 0x0000000000200000ULL},
    {1706432, 0x03, 0x05, 0x0000000000200000ULL},
    {1706432, 0x03, 0x06, 0x0000000000200000ULL},
    {1706432, 0x03, 0x07, 0x0000000000200000ULL},
    {1706432, 0x03, 0x08, 0x0000000000200000ULL},
    {1706432, 0x03, 0xff, 0x0000000000300000ULL},
    {1706432, 0xff, 0xff, 0x0000000000300000ULL},
    {1706433, 0x01, 0xff, 0x0000000000080000ULL},
    {1706433, 0xff, 0xff, 0x0000000000080000ULL},
    {1706434, 0x01, 0xff, 0x0000000000000008ULL},
    {1706434, 0xff, 0xff, 0x0000000000000008ULL},
    {1706435, 0x01, 0xff, 0x0000000001000000ULL},
    {1706435, 0xff, 0xff, 0x0000000001000000ULL},
    {1706558, 0x02, 0xff, 0x0000000000400000ULL},
    {1706558, 0x03, 0xff, 0x0000000000800000ULL},
    {1706558, 0xff, 0xff, 0x0000000000c00000ULL},
    {1706973, 0x01, 0x04, 0x0000000000100000ULL},
    {1706973, 0x01, 0x05, 0x0000000000100000ULL},
    {1706973, 0x01, 0x09, 0x0000000000200000ULL},
    {1706973, 0x01, 0xff, 0x0000000000300000ULL},
    {1706973, 0x02, 0x03, 0x0000000000200000ULL},
    {1706973, 0x02, 0x08, 0x0000000000100000ULL},
    {1706973, 0x02, 0x09, 0x0000000000100000ULL},
    {1706973, 0x02, 0xff, 0x0000000000300000ULL},
    {1706973, 0x03, 0x00, 0x0000000000100000ULL},
    {1706973, 0x03, 0x04, 0x0000000000200000ULL},
    {1706973, 0x03, 0x08, 0x0000000000200000ULL},
    {1706973, 0x03, 0xff, 0x0000000000300000ULL},
    {1706973, 0xff, 0xff, 0x0000000000300000ULL},
    {1706974, 0x02, 0xff, 0x0000000000100000ULL},
    {1706974, 0x03, 0x00, 0x0000000000100000ULL},
    {1706974, 0x03, 0x04, 0x0000000000200000ULL},
    {1706974, 0x03, 0x08, 0x0000000000200000ULL},
    {1706974, 0x03, 0xff, 0x0000000000300000ULL},
    {1706974, 0xff, 0xff, 0x0000000000300000ULL},
    {1706976, 0x01, 0xff, 0x0000000000080000ULL},
    {1706976, 0x02, 0xff, 0x0000000008000000ULL},
    {1706976, 0x03, 0xff, 0x0000000008000000ULL},
    {1706976, 0xff, 0xff, 0x0000000008080000ULL},
    {1707290, 0x01, 0xff, 0x0000000040000000ULL},
    {1707290, 0x02, 0xff, 0x0000000040000000ULL},
    {1707290, 0xff, 0xff, 0x0000000040000000ULL},
    {1707450, 0x01, 0xff, 0x0000000000001000ULL},
    {1707450, 0x03, 0xff, 0x0000000000003000ULL},
    {1707450, 0x04, 0xff, 0x0000000000003000ULL},
    {1707450, 0x05, 0xff, 0x0000000000003000ULL},
    {1707450, 0x06, 0xff, 0x0000000000003000ULL},
    {1707450, 0x07, 0xff, 0x0000000000001000ULL},
    {1707450, 0xff, 0xff, 0x0000000000003000ULL},
    {1707452, 0x03, 0xff, 0x0000000000003000ULL},
    {1707452, 0x04, 0xff, 0x0000000000003000ULL},
    {1707452, 0x05, 0xff, 0x0000000000003000ULL},
    {1707452, 0xff, 0xff, 0x0000000000003000ULL},
    {1707458, 0x01, 0xff, 0x0000000040000000ULL},
    {1707458, 0x02, 0xff, 0x0000000040000000ULL},
    {1707458, 0xff, 0xff, 0x0000000040000000ULL},
    {1707780, 0x01, 0xff, 0x0000000002000000ULL},
    {1707780, 0x02, 0xff, 0x0000000002000000ULL},
    {1707780, 0xff, 0xff, 0x0000000002000000ULL},
    {1707926, 0x01, 0xff, 0x0000000002000000ULL},
    {1707926, 0x02, 0xff, 0x0000000002000000ULL},
    {1707926, 0xff, 0xff, 0x0000000002000000ULL},
    {1708171, 0x01, 0xff, 0x0000000000000010ULL},
    {1708171, 0x03, 0xff, 0x0000000000000010ULL},
    {1708171, 0x05, 0xff, 0x0000000000000010ULL},
    {1708171, 0x06, 0xff, 0x0000000000000010ULL},
    {1708171, 0xff, 0xff, 0x0000000000000010ULL},
    {1708172, 0x03, 0xff, 0x0000000000000010ULL},
    {1708172, 0x04, 0xff, 0x0000000000000010ULL},
    {1708172, 0xff, 0xff, 0x0000000000000010ULL},
    {1708405, 0x01, 0xff, 0x0000000000000040ULL},
    {1708405, 0x03, 0xff, 0x0000000000000040ULL},
    {1708405, 0x04, 0xff, 0x0000000000000040ULL},
    {1708405, 0x05, 0xff, 0x0000000000000040ULL},
    {1708405, 0xff, 0xff, 0x0000000000000040ULL},
    {1708415, 0x01, 0xff, 0x0000000000000020ULL},
    {1708415, 0xff, 0xff, 0x0000000000000020ULL},
    {1708687, 0x01, 0xff, 0x0000000000001000ULL},
    {1708687, 0x03, 0xff, 0x0000000000001000ULL},
    {1708687, 0x04, 0xff, 0x0000000000001000ULL},
    {1708687, 0x05, 0xff, 0x0000000000001000ULL},
    {1708687, 0x06, 0xff, 0x0000000000002000ULL},
    {1708687, 0x07, 0xff, 0x0000000000001000ULL},
    {1708687, 0xff, 0xff, 0x0000000000003000ULL},
    {1708762, 0x03, 0xff, 0x0000000000000800ULL},
    {1708762, 0xff, 0xff, 0x0000000000000800ULL},
    {1708873, 0x01, 0xff, 0x0000000000000400ULL},
    {1708873, 0x03, 0xff, 0x0000000000000400ULL},
    {1708873, 0x04, 0xff, 0x0000000000000400ULL},
    {1708873, 0x05, 0x00, 0x0000000000000400ULL},
    {1708873, 0x05, 0x01, 0x0000000000000400ULL},
    {1708873, 0x05, 0x02, 0x0000000000000200ULL},
    {1708873, 0x05, 0x03, 0x0000000000000200ULL},
    {1708873, 0x05, 0x04, 0x0000000000000200ULL},
    {1708873, 0x05, 0x05, 0x0000000000000200ULL},
    {1708873, 0x05, 0x06, 0x0000000000000200ULL},
    {1708873, 0x05, 0x07, 0x0000000000000200ULL},
    {1708873, 0x05, 0x08, 0x0000000000000200ULL},
    {1708873, 0x05, 0x09, 0x0000000000000200ULL},
    {1708873, 0x05, 0xff, 0x0000000000000600ULL},
    {1708873, 0xff, 0xff, 0x0000000000000600ULL},
    {1709114, 0x01, 0xff, 0x0000000000000004ULL},
    {1709114, 0x02, 0xff, 0x0000000000000004ULL},
    {1709114, 0x03, 0xff, 0x0000000000000004ULL},
    {1709114, 0x04, 0xff, 0x0000000000000004ULL},
    {1709114, 0xff, 0xff, 0x0000000000000004ULL},
    {1709217, 0x01, 0xff, 0x0000000000000010ULL},
    {1709217, 0x03, 0xff, 0x0000000000000010ULL},
    {1709217, 0x06, 0xff, 0x0000000000000010ULL},
    {1709217, 0xff, 0xff, 0x0000000000000010ULL},
    {1709218, 0x03, 0xff, 0x0000000000000010ULL},
    {1709218, 0xff, 0xff, 0x0000000000000010ULL},
    {1709231, 0x01, 0xff, 0x0000000000004000ULL},
    {1709231, 0x02, 0xff, 0x0000000000004000ULL},
    {1709231, 0xff, 0xff, 0x0000000000004000ULL},
    {1709232, 0x01, 0xff, 0x0000000000000001ULL},
    {1709232, 0x02, 0x00, 0x0000000000000001ULL},
    {1709232, 0x02, 0x01, 0x0000000000000001ULL},
    {1709232, 0x02, 0x02, 0x0000000000000001ULL},
    {1709232, 0x02, 0x03, 0x0000000010000000ULL},
    {1709232, 0x02, 0x04, 0x0000000010000000ULL},
    {1709232, 0x02, 0x05, 0x0000000010000000ULL},
    {1709232, 0x02, 0x06, 0x0000000010000000ULL},
    {1709232, 0x02, 0x07, 0x0000000010000000ULL},
    {1709232, 0x02, 0x08, 0x0000000010000000ULL},
    {1709232, 0x02, 0x09, 0x0000000010000000ULL},
    {1709232, 0x02, 0xff, 0x0000000010000001ULL},
    {1709232, 0x03, 0xff, 0x0000000010000000ULL},
    {1709232, 0xff, 0xff, 0x0000000010000001ULL},
    {1709233, 0x01, 0xff, 0x0000000000000100ULL},
    {1709233, 0x03, 0xff, 0x0000000000000100ULL},
    {1709233, 0x04, 0xff, 0x0000000000000100ULL},
    {1709233, 0xff, 0xff, 0x0000000000000100ULL},
    {1709241, 0x01, 0xff, 0x0000000084000000ULL},
    {1709241, 0xff, 0xff, 0x0000000084000000ULL},
    {1709433, 0x01, 0xff, 0x0000000000000400ULL},
    {1709433, 0x03, 0xff, 0x0000000000000400ULL},
    {1709433, 0x04, 0xff, 0x0000000000000400ULL},
    {1709433, 0x05, 0xff, 0x0000000000000200ULL},
    {1709433, 0xff, 0xff, 0x0000000000000600ULL},
    {1709516, 0x01, 0xff, 0x0000000000000080ULL},
    {1709516, 0xff, 0xff, 0x0000000000000080ULL},
    {1807663, 0x01, 0xff, 0x0000000001000000ULL},
    {1807663, 0xff, 0xff, 0x0000000001000000ULL},
    {3608726, 0x01, 0xff, 0x0000000000008000ULL},
    {3608726, 0x03, 0xff, 0x0000000000008000ULL},
    {3608726, 0x04, 0xff, 0x0000000000008000ULL},
    {3608726, 0x05, 0xff, 0x0000000000008000ULL},
    {3608726, 0x06, 0xff, 0x0000000000008000ULL},
    {3608726, 0x07, 0xff, 0x0000000000008000ULL},
    {3608726, 0x08, 0xff, 0x0000000000008000ULL},
    {3608726, 0xff, 0xff, 0x0000000000008000ULL},
    {3608727, 0x01, 0xff, 0x0000000000000002ULL},
    {3608727, 0x02, 0xff, 0x0000000000000002ULL},
    {3608727, 0x03, 0xff, 0x0000000000000002ULL},
    {3608727, 0x04, 0xff, 0x0000000000000002ULL},
    {3608727, 0x05, 0xff, 0x0000000020000000ULL},
    {3608727, 0x06, 0xff, 0x0000000020000000ULL},
    {3608727, 0x07, 0xff, 0x0000000020000000ULL},
    {3608727, 0xff, 0xff, 0x0000000020000002ULL},
    {3608729, 0x01, 0xff, 0x0000000000020000ULL},
    {3608729, 0x02, 0xff, 0x0000000000020000ULL},
    {3608729, 0x03, 0xff, 0x0000000000020000ULL},
    {3608729, 0x04, 0xff, 0x0000000000010000ULL},
    {3608729, 0x05, 0xff, 0x0000000000010000ULL},
    {3608729, 0x06, 0xff, 0x0000000000020000ULL},
    {3608729, 0xff, 0xff, 0x0000000000030000ULL},
    {3608934, 0x01, 0xff, 0x0000000000000100ULL},
    {3608934, 0x03, 0xff, 0x0000000000000100ULL},
    {3608934, 0x04, 0xff, 0x0000000000000100ULL},
    {3608934, 0xff, 0xff, 0x0000000000000100ULL},
    {3609606, 0x01, 0xff, 0x0000000000000004ULL},
    {3609606, 0x02, 0xff, 0x0000000000000004ULL},
    {3609606, 0x03, 0xff, 0x0000000000000004ULL},
    {3609606, 0x04, 0xff, 0x0000000000000004ULL},
    {3609606, 0xff, 0xff, 0x0000000000000004ULL},
    {0, 0, 0, 0},
};
